name: Continous Integration

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Define NodeJS Version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      # Install project dependencies
      - run: npm ci
      # Check code formatting based on script defined - Prettier
      - run: npm run format:check
      # Run Automated tests
      - run: npm test -- --coverage
      # Define enviromental variable to avoid interactive terminal
        env:
          CI: true
      # Upload generated code coverage as an Artifact