name: Continous Integration

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Define NodeJS Version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      # Install project dependencies
      - run: npm ci
      # Check code formatting based on script defined - Prettier
      - run: npm run format:check
      - run: npm rum format
      # Run Automated tests
      - run: npm test -- --coverage
        # Define enviromental variable to avoid interactive terminal
        env:
          CI: true
      # Upload generated code coverage as an Artifact

    # Workflow to trigger when there is a push to the develop repo
      - name: Build project
        if: github.event_name == 'push'
        run: |
          npm run build
          npm install --global surge

      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npm surge --project ./build --domain http://honorable-bait.surge.sh/
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}