name: Send Notification On Every New Version Released

on:
  release:
    types:
      - "published"

jobs:
  Slack-Message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Hello Team, We have a New Release ${{ github.event.release.tag_name }},
          < ${{ github.event.release.html_url }} Please lets do well to check it out now and share your observations.>"}' ${{ secrets.SLACK_WEBHOOK }}
