name: Notify on release

on:
  release:
    types:
      - "published"

jobs:
  Slack-Message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Hello Team, We have a New Release ${{ github.event.release.tag_name }} is out,
          < ${{ github.event.release.html_url }} | check it out now.>"}' ${{ secrets.SLACK_WEBHOOK }}
